project:
    type: website
    output-dir: docs
    resources:
        - documentation/
        - images/
        - data/

website:
    title: 'Habib Goloba'
    # Image taken from: https://fontawesome.com/icons/square-pied-piper?f=classic&s=brands&pc=%23FFD43B&sc=%23FFD43B
    favicon: images/square-pied-piper-brands.svg
    navbar:
        title: false
        logo: images/square-pied-piper-brands.svg
        right:
            - href: index.qmd
              text: Home
            - about.qmd
            - text: Projects
              menu:
                  - href: project1.qmd
                    text: Power BI
                  - href: project2.qmd
                    text: Overbooking Strategy Analysis
                  - href: project3.qmd
                    text: Kaggle SQL Dataset
            - href: contact.qmd
              text: Contact Me

    page-footer:
        background: dark
        left: © Copyright 2025, Habib Goloba
        right: This website is built with [Quarto](https://quarto.org/){target=_blank}

format:
    html:
        theme:
            - lux
            - brand
        css: styles.css
        toc: true
