project:
    type: website
    output-dir: docs

website:
    title: 'Habib Goloba'
    navbar:
        right:
            - href: index.qmd
              text: Home
            - about.qmd
    page-footer:
        background: light #or dark
        left: © Copyright 2025, Habib Goloba
        right: This website is built with [Quarto](https://quarto.org/){target=_blank}

format:
    html:
        theme:
            - lux
            - brand
        css: styles.css
        toc: true
