---
title: "About Me"
about:
    template: jolla
---

### Biography

___

My name is Habib Goloba, a driven student at Dublin City University specialising in Business Analytics. I am working towards a Bachelor of Business Studies, with a deep focus on utilising a variety of analytical platforms, tools, and methodologies. My academic journey is complemented by significant hands-on experience, including my role as a Depositary Intern Analyst at Societe Generale. In this position, I've gained practical insights into financial analysis, enhancing my skills in data manipulation and analysis with advanced tools such as Python, SQL, and Power BI. These skills have been applied and expanded in college modules like Professional Business Analytics Portfolio, Data Mining & Predictive Analytics, and Workflow and Data Management.

I am committed to using my analytical expertise to significantly influence business strategies and operational efficiencies within cutting-edge corporate settings. My goal is to continuously develop my skill set and knowledge base through ongoing education and real-world applications. I aim to contribute to and lead projects that leverage big data to drive innovation, optimise processes, and enhance decision-making.

My career aspiration is to rise to a leadership role within the technology and analytics sector, where I can set industry standards and mentor the next generation of business analysts. This ambition is a professional aim and a personal commitment to excel in a field that merges my interests in technology, business, and problem-solving. By aligning with organisations that value innovation and data-driven decision-making, I strive to make a significant impact on the business landscape and achieve excellence in my future endeavours.